spring:
  application:
    name: social_server
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:web_server_api;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  kafka:
    topic:
      subscription-request: v1.subscription.request
      subscription-reply: v1.subscription.response
      comment-created: v1.event.comment-created
      user-joined: v1.event.user-joined
    consumer:
      bootstrap-servers: localhost:9092
      group-id: api
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092
server:
  port: 8080
jwt:
  token:
    header: api_key
    issuer: social_server
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 0
cloud:
  aws:
    s3:
      region: ap-northeast-2
      accessKey: ACCESS_KEY
      secretKey: SECRET_KEY
      url: https://s3.ap-northeast-2.amazonaws.com
      bucketName: prgrms-web-bjs
eventbus:
  asyncPoolCore: 1
  asyncPoolMax: 4
  asyncPoolQueue: 100
